name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-lint-test:
    name: Build, Lint, and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.23'

      - name: Install Dependencies
        run: go mod download

      - name: Run Go Fmt
        run: |
           fmt_count=$(go fmt ./... | wc -l)
           if [ $fmt_count -ne 0 ]; then
             echo "Go code is not formatted. Please run 'go fmt ./...'"
             exit 1
           fi

      - name: Run Go Vet
        run: go vet ./...

      - name: Run Staticcheck
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@latest
          staticcheck ./...

      - name: Run Tests
        run: go test -v ./...

      - name: Build Application
        run: go build -v -o cacher ./cmd/main.go
